// <auto-generated />
namespace HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HesabatIn3AndTheHagz5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HesabatIn3AndTheHagz5));
        
        string IMigrationMetadata.Id
        {
            get { return "201811012208294_HesabatIn3AndTheHagz5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
